---


#Docker Installed version
docker_compose_version: 1.21.2
docker_ce_version: 18.06.0~ce~3-0~ubuntu

timezone: Africa/Bamako

dns_resolv_searchpath:
  - 'dgimali.org'

dns_server_list:
  - 10.30.1.48
  - 8.8.8.8
  
docker_user: "{{ vault_docker_user }}"
docker_pwd: "{{ vault_docker_pwd }}"

#MALI OWN DATADOG ACCOUNT
dd_key: "{{ vault_dd_key }}"

#Feature Flags - Enable/Disable
dd_enabled: no #We're using datadog in docker now. This var comes from datadog role.
dd_installed: False #We won't keep installed in the VM.
is_mongo_on_docker_enabled: False # we using dedicated on OS installed instances here.
is_swarm_mode_enabled: True # Swarm Mode Enabled
is_tax_calculator_enabled: False
is_datadog_on_docker: True
is_dss_present: True

node_installed: False
jenkins_slave_node: False
pull_images: no


#attossato docker-swarm role settings
skip_engine: True
skip_docker_py: True


#Docker Containers Deployed
efiling_ui_image_version: 1.9.1
efiling_api_image_version: 1.9.1
dss_sigtas_api_image_version: 0.9.0

#update_cart_schedule: "0 1 * * *"

#2FA disabled for now
twofactor_public: 'true'
twofactor_private: 'false'
twofactor_passcode_expire: 15 #in minutes


port: 8080
node_env: production
debug: 'true'
logging_level: info

public_ui_url: https://e-impot.dgi.gouv.ml:443/
admin_ui_url: https://e-impot.dgi.gouv.ml:4203/

sigtas_api_url: 'http://vm-ap-dgi-24.dgimali.org:9767/'
sigtas_api_services_path: 'services/sigtas/'
sigtas_api_auth_path: 'token/'
sigtas_api_secured: false
sigtas_api_key: "{{ vault_sigtas_api_key }}"
sigtas_api_secret :  "{{ vault_sigtas_api_secret }}"

calculation_api_url: http://{{ansible_ssh_host}}:8082/
calculation_api_services_path: api/
calculation_api_secured: 'false'

cache_url: localhost:6379

database_url: "vm-bd-dgi-12.dgimali.org:27017,vm-bd-dgi-13.dgimali.org:27017,vm-bd-dgi-14.dgimali.org:27017"

cache_timer_short_hr: 1
cache_timer_medium_hr: 2
cache_timer_long_hr: 3

db_user: "{{ vault_db_user }}"
db_pass: "{{ vault_db_pass }}"
db_name: efiling

seed_admin_username: "{{ vault_seed_admin_username }}"
seed_admin_password: "{{ vault_seed_admin_password }}"
seed_admin_email: efi4MaliAdmin@sogematech.com

seed_tax_system_username: "{{ vault_seed_tax_system_username }}"
seed_tax_system_password: "{{ vault_seed_tax_system_password }}"
seed_tax_system_email: efi4MaliTaxSystem@sogematech.com

oracle_host: vm-bd-dgi-02.dgimali.org
oracle_port: 1521
oracle_user: "{{ vault_oracle_user }}"
oracle_pwd: "{{ vault_oracle_pwd }}"
oracle_db: sgt30prd
wso2_logging_level: INFO

java_oracle_prefix: jdk
flyway_root: /opt/flyway
flyway_config:
 database:
   host: localhost
   port: 5432
   dbms: postgresql
   name: wso2dss
   user: postgres
   password: postgres
 schemas: public
flyway_locations: filesystem:/opt/migrations/   
