---

#Docker Installed version
docker_compose_version: 1.21.2
docker_ce_version: 18.03.1~ce-0~ubuntu

  
docker_user: "{{ vault_docker_user }}"
docker_pwd: "{{ vault_docker_pwd }}"

#Feature Flags - Enable/Disable
dd_enabled: no #We're using datadog in docker now. This var comes from datadog role.
dd_installed: False #We won't keep installed in the VM.
is_mongo_on_docker_enabled: False # we using dedicated on OS installed instances here.
is_swarm_mode_enabled: False # Swarm Mode Enabled
## Tax calculation feature (With Sigtas or tax_calculator system) (DDC-28)
is_tax_calculator_enabled: False
is_tax_calc_feature_enabled: 'false'
update_taxpayer_access_schedule: '*/3 * * * *'
is_datadog_on_docker: false
is_dss_present: True
is_api_scheduler_enabled: True
#Payment processing update cart interval - UBA specific
update_cart_schedule: "0 1 * * *"

#efiling_api connection retrials mongodb
db_reconnect_limit: 0
db_reconnect_interval: 5000

node_installed: False
jenkins_slave_node: False
pull_images: True
wso2_logging_level: INFO
is_filebeat_on_docker: False

#attossato docker-swarm role settings
skip_engine: True
skip_docker_py: True

#Docker Containers Deployed
efiling_ui_image_version: 1.14.7
efiling_api_image_version: 1.14.7
dss_sigtas_api_image_version: 0.9.19

#2FA disabled for now
twofactor_public: 'true'
twofactor_private: 'false'
twofactor_passcode_expire: 15 #in minutes


#Login brute force protection
slow_seconds: 1
login_lock: 'true'
lock_minutes: 1
login_captcha: 'true'
captcha_minutes: 20
max_failed_attempts: 5

max_file_size: 10000000 # in bytes 10mb



port: 8080
node_env: production
debug: 'true'
logging_level: info

public_ui_url: https://e-impot-for.dgi.gouv.ml:443/
admin_ui_url: https://e-impot-for.dgi.gouv.ml:4203/

sigtas_api_url: 'http://vm-ap-dgi-20.dgimali.org:9767/'
sigtas_api_services_path: 'services/sigtas/'
sigtas_api_auth_path: 'token/'
sigtas_api_secured: false
sigtas_api_key: "{{ vault_sigtas_api_key }}"
sigtas_api_secret :  "{{ vault_sigtas_api_secret }}"

calculation_api_url: http://{{ansible_ssh_host}}:8082/
calculation_api_services_path: api/
calculation_api_secured: 'false'

cache_url: localhost:6379

database_url: "vm-bd-dgi-10.dgimali.org:27017"
cache_timer_short_hr: 0
cache_timer_medium_hr: 0
cache_timer_long_hr: 0

db_user: "{{ vault_db_user }}"
db_pass: "{{ vault_db_pass }}"
db_name: efiling

seed_admin_username: "{{ vault_seed_admin_username }}"
seed_admin_password: "{{ vault_seed_admin_password }}"
seed_admin_email: efi4MaliAdmin@sogematech.com

seed_tax_system_username: "{{ vault_seed_tax_system_username }}"
seed_tax_system_password: "{{ vault_seed_tax_system_password }}"
seed_tax_system_email: efi4MaliTaxSystem@sogematech.com

oracle_host: vm-bd-dgi-01.dgimali.org
oracle_port: 1521
oracle_user: sigtas_api
oracle_pwd: dbaadmin
oracle_db: sgt30for

java_oracle_prefix: jdk
flyway_root: /opt/flyway
flyway_config:
 database: 
   host: localhost
   port: 5432
   dbms: postgresql
   name: wso2dss
   user: postgres
   password: postgres
 schemas: public
flyway_locations: filesystem:/opt/migrations/
