---
timezone: Africa/Timbuktu

dd_enabled: yes
dd_installed: True

mongodb_package: mongodb-org
mongodb_version: "3.4"

mongodb_user_update_password: "on_create" # MongoDB user password update default policy
mongodb_manage_service: true

dns_resolv_searchpath:
  - 'dgimali.org'

dns_server_list:
  - 10.30.1.4
  - 8.8.8.8

#Users/Credentials
mongodb_user_admin_name: "{{vault_mongodb_user_admin_name}}"
mongodb_user_admin_password: "{{vault_mongodb_user_admin_password}}"

mongodb_root_admin_name: "{{vault_mongodb_root_admin_name}}"
mongodb_root_admin_password: "{{vault_mongodb_root_admin_password}}"

mongodb_root_backup_name: "{{vault_mongodb_root_backup_name}}"
mongodb_root_backup_password: "{{vault_mongodb_root_backup_password}}"

mongodb_security_authorization: 'enabled'
mongodb_keyfile_content: "{{ vault_mongodb_keyfile_content }}"

mongodb_users: "{{ vault_efiling_user }}"

## net Options
mongodb_net_bindip: 0.0.0.0     # Comma separated list of ip addresses to listen on
mongodb_net_http_enabled: false      # Enable http interface
mongodb_net_ipv6: false             # Enable IPv6 support (disabled by default)
mongodb_net_maxconns: 51100         # Max number of simultaneous connections
mongodb_net_port: 27017   

mongodb_daemon_name: "{{ 'mongod' if ('mongodb-org' in mongodb_package) else 'mongodb' }}"
mongodb_storage_engine: 'wiredTiger'

## systemLog Options
## The destination to which MongoDB sends all log output. Specify either 'file' or 'syslog'.
## If you specify 'file', you must also specify mongodb_systemlog_path.
mongodb_systemlog_destination: "file"
mongodb_systemlog_logappend: true                                        # Append to logpath instead of over-writing
mongodb_systemlog_path: /var/log/mongodb/{{ mongodb_daemon_name }}.log   # Log file to send write to instead of stdout

# Log rotation
mongodb_logrotate: true                             # Rotate mongodb logs.
mongodb_logrotate_options:
  - compress
  - copytruncate
  - daily
  - dateext
  - rotate 7
  - size 10M




