---

environment_name: pprd-ml
ansible_ssh_user: "{{ vault_ansible_ssh_user }}"
ansible_ssh_pass: "{{ vault_ansible_ssh_pass }}"
ansible_become_pass: "{{ vault_ansible_ssh_pass }}"

dd_key: "{{ vault_dd_key }}"
dd_enabled: no
dd_installed: False

etc_save_hosts:
    - name: "{{ ansible_ssh_host }}"
      ip: 127.0.0.1

timezone: Africa/Bamako

dns_resolv_searchpath:
  - 'dgimali.org'

dns_server_list:
  - 10.30.1.48
  - 10.30.1.49
  - 8.8.8.8
