---

full_hostname: vm-ap-dgi-23.dgimali.org

is_dss_present: False

available_docker_services:
  - efiling_ui 
  - efiling_ui_admin
  - efiling_api
  - datadog
  
datadog_monitored_docker_services: 
  - efiling_ui 
  - efiling_ui_admin
  - efiling_api